{{- $name := include "sapact.name" . -}}
{{- $regionalisedname := include "sapact.regionalisedname" . -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $regionalisedname }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $name }}
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.AKSClusterSAName }}
      containers:
        - name: {{ $name }}
          image: computeaksacr.azurecr.io/{{ $name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: sapact-port
              containerPort: 8080
              protocol: TCP
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.environment | quote }}
          - name: "REGION_CODE"
            value: {{ .Values.regioncode | quote }}
          - name: "SAPACT_CONFIGURATION_URL"
            value: {{ .Values.configKeyVault | quote }}
          
      nodeSelector:
        agentpool: platform