{{- if eq .Values.regioncode "ne" }}
apiVersion: devops.uniphar.ie/v1
kind: PlatformDataPilotSqlDatabase
metadata:
  name: sapact-dev-db
  namespace: platform-app
spec:
# same as it was originally
  maxSizeGB: 250
  access:
    workloadIdentity:
      name: compute-aks-platform-app-dev-k8s-sa
      namespace: platform-app
    entraIdGroup:
      name: DevOps High-RoleAssignable
{{- end }}