namespace SapAct.Tests.Services;

[TestClass]
public class SQLServiceTests
{
	private static IServiceProvider? _serviceProvider;
	private static IConfiguration? _config;

	[ClassInitialize]
	public static void ClassInitialize(TestContext testContext)
	{
		var azureKeyVaultName = Environment.GetEnvironmentVariable(Consts.KEYVAULT_CONFIG_URL);

		DefaultAzureCredential credential = new();

		_config = new ConfigurationBuilder()
			.AddAzureKeyVault(new(azureKeyVaultName!), credential)
			.Build();

		_serviceProvider = new ServiceCollection()
			.AddTransient((sp) => new SqlConnection(_config.GetSQLConnectionString()))
			.BuildServiceProvider();
	}

	[TestMethod, TestCategory("Unit")]
	public async Task ProjectSchemaFlowTest()
	{
		//arrange
		var sut = new SQLService(_serviceProvider!, Mock.Of<ILogger<SQLService>>());

        var jsontext = @"
[
    {
        ""id"": ""23EDCD53609F1EEFA0CC814827B9D2E3"",
        ""objectType"": ""MATERIALDOCUMENT"",
        ""objectKey"": ""20244900001565"",
        ""system"": ""SDV"",
        ""client"": ""100"",
        ""eventTimestamp"": ""2024-10-04T15:19:25Z"",
        ""dataVersion"": ""1.0.0"",
        ""eventType"": ""Created"",
        ""data"": {
            ""materialDocumentYear"": 2024,
            ""materialDocument"": ""4900001565"",
            ""inventoryTransactionType"": ""WA"",
            ""documentDate"": ""2024-10-04"",
            ""postingDate"": ""2024-10-04"",
            ""creationDate"": ""2024-10-04"",
            ""creationTime"": ""16:19:24"",
            ""createdByUser"": ""RFCUSER"",
            ""materialDocumentHeaderText"": """",
            ""referenceDocument"": ""CW01100000000442"",
            ""versionForPrintingSlip"": ""2"",
            ""manualPrintIsTriggered"": """",
            ""ctrlPostForExtWhseMgtSys"": ""2"",
            ""goodsMovementCode"": ""04"",
            ""plant"": ""1100"",
            ""storageLocation"": ""0001"",
            ""issuingOrReceivingPlant"": ""1100"",
            ""issgOrRcvgStorageLoc"": ""0005"",
            ""toItems"": [
                {
                    ""materialDocumentYear"": 2024,
                    ""materialDocument"": ""4900001565"",
                    ""materialDocumentItem"": 1,
                    ""material"": ""000000000000753741"",
                    ""plant"": ""1100"",
                    ""storageLocation"": ""0001"",
                    ""batch"": """",
                    ""goodsMovementType"": ""325"",
                    ""inventoryStockType"": ""07"",
                    ""inventoryValuationType"": """",
                    ""inventorySpecialStockType"": """",
                    ""supplier"": """",
                    ""customer"": """",
                    ""salesOrder"": """",
                    ""salesOrderItem"": 0,
                    ""salesOrderScheduleLine"": 0,
                    ""purchaseOrder"": """",
                    ""purchaseOrderItem"": 0,
                    ""wbsElement"": """",
                    ""manufacturingOrder"": """",
                    ""manufacturingOrderItem"": 0,
                    ""goodsMovementRefDocType"": """",
                    ""goodsMovementReasonCode"": 0,
                    ""delivery"": """",
                    ""deliveryItem"": 0,
                    ""accountAssignmentCategory"": """",
                    ""costCenter"": """",
                    ""controllingArea"": ""1000"",
                    ""costObject"": """",
                    ""glAccount"": """",
                    ""functionalArea"": """",
                    ""profitabilitySegment"": 0,
                    ""profitCenter"": ""1100000000"",
                    ""masterFixedAsset"": """",
                    ""fixedAsset"": """",
                    ""materialBaseUnit"": ""EA"",
                    ""quantityInBaseUnit"": 80.000,
                    ""entryUnit"": ""EA"",
                    ""quantityInEntryUnit"": 80.000,
                    ""companyCodeCurrency"": ""EUR"",
                    ""gdsMvtExtAmtInCoCdeCrcy"": 0,
                    ""amtInclVatInCoCodeCrcy"": 0,
                    ""fiscalYear"": 2024,
                    ""fiscalYearPeriod"": 2024010,
                    ""fiscalYearVariant"": ""K4"",
                    ""issgOrRcvgMaterial"": ""000000000000753741"",
                    ""issgOrRcvgBatch"": """",
                    ""issuingOrReceivingPlant"": ""1100"",
                    ""issgOrRcvgStorageLoc"": ""0005"",
                    ""issuingOrReceivingStockTyp"": ""07"",
                    ""issgOrRcvgSpclStockInd"": """",
                    ""issuingOrReceivingValType"": """",
                    ""isCompletelyDelivered"": """",
                    ""materialDocumentItemText"": """",
                    ""goodsRecipientName"": """",
                    ""unloadingPointName"": """",
                    ""shelfLifeExpirationDate"": """",
                    ""manufactureDate"": """",
                    ""serialNmbrAreCreatdAutomly"": """",
                    ""reservation"": 0,
                    ""reservationItem"": 0,
                    ""reservationIsFinallyIssued"": """",
                    ""specialStockIdfgSalesOrder"": """",
                    ""splStockIdfgSlsOrderItem"": 0,
                    ""specialStockIdfgWbsElement"": """",
                    ""isAutomaticallyCreated"": """",
                    ""materialDocumentLine"": 1,
                    ""materialDocumentParentLine"": 0,
                    ""hierarchyNodeLevel"": 0,
                    ""goodsMovementIsCancelled"": """",
                    ""reversedMaterialDocumentYr"": 0,
                    ""reversedMaterialDocument"": """",
                    ""reversedMaterialDocumentItm"": 0,
                    ""referenceDocumentFiscalYear"": 0,
                    ""invtryMgmtRefDocumentItem"": 0,
                    ""invtryMgmtreferenceDocument"": """",
                    ""materialDocumentPostingType"": """",
                    ""inventoryUsabilityCode"": """",
                    ""ewmWarehouse"": """",
                    ""ewmStorageBin"": """",
                    ""crossPlantConfigurableProd"": """",
                    ""productCharacteristic1"": """",
                    ""productCharacteristic2"": """",
                    ""productCharacteristic3"": """",
                    ""productSeasonYear"": """",
                    ""productSeason"": """",
                    ""productCollection"": """",
                    ""productTheme"": """",
                    ""stockSegment"": """",
                    ""issgOrRcvgStockSegment"": """",
                    ""yyuniSuppCode"": ""A0081"",
                    ""debitCreditIndicator"": ""H"",
                    ""transactionCode"": ""MB1B"",
                    ""toSerialNumber"": [],
                    ""toSupplier"": {
                        ""supplier"": """",
                        ""alternativePayeeAccountNmbr"": """",
                        ""authorizationGroup"": """",
                        ""createdByUser"": """",
                        ""creationDate"": """",
                        ""customer"": """",
                        ""paymentIsBlockedForSupplr"": """",
                        ""postingIsBlocked"": """",
                        ""purchasingIsBlocked"": """",
                        ""supplierAccountGroup"": """",
                        ""supplierFullName"": """",
                        ""supplierName"": """",
                        ""vatRegistration"": """",
                        ""birthDate"": """",
                        ""concatInternationalLocNo"": """",
                        ""deletionIndicator"": """",
                        ""fiscalAddress"": """",
                        ""industry"": """",
                        ""internationalLocationNumber1"": 0,
                        ""internationalLocationNumber2"": 0,
                        ""internationalLocationNumber3"": 0,
                        ""isNaturalPerson"": """",
                        ""responsibleType"": """",
                        ""splrQltyInProcCrtfnValTo"": """",
                        ""suplrQualityManagementSys"": """",
                        ""supplierCorporateGroup"": """",
                        ""supplierProcurementBlock"": """",
                        ""taxNumber1"": """",
                        ""taxNumber2"": """",
                        ""taxNumber3"": """",
                        ""taxNumber4"": """",
                        ""taxNumber5"": """",
                        ""taxNumberResponsible"": """",
                        ""taxNumberType"": """",
                        ""suplrProofOfDelivRlvtCode"": """",
                        ""isBusinessPurposeCompleted"": """",
                        ""brTaxIsSplit"": """",
                        ""dataExchangeInstructionKey"": """"
                    },
                    ""toCustomer"": {
                        ""customer"": """",
                        ""authorizationGroup"": """",
                        ""billngIsBlockedForCustomer"": """",
                        ""createdByUser"": """",
                        ""creationDate"": """",
                        ""customerAccountGroup"": """",
                        ""customerClassification"": """",
                        ""customerFullName"": """",
                        ""customerName"": """",
                        ""deliveryIsBlocked"": """",
                        ""nfPartnerIsNaturalPerson"": """",
                        ""orderIsBlockedForCustomer"": """",
                        ""postingIsBlocked"": """",
                        ""supplier"": """",
                        ""customerCorporateGroup"": """",
                        ""fiscalAddress"": """",
                        ""industry"": """",
                        ""industryCode1"": """",
                        ""industryCode2"": """",
                        ""industryCode3"": """",
                        ""industryCode4"": """",
                        ""industryCode5"": """",
                        ""internationalLocationNumber1"": 0,
                        ""nielsenRegion"": """",
                        ""responsibleType"": """",
                        ""taxNumber1"": """",
                        ""taxNumber2"": """",
                        ""taxNumber3"": """",
                        ""taxNumber4"": """",
                        ""taxNumber5"": """",
                        ""taxNumberType"": """",
                        ""vatRegistration"": """",
                        ""deletionIndicator"": """",
                        ""expressTrainStationName"": """",
                        ""trainStationName"": """",
                        ""cityCode"": """",
                        ""county"": """",
                        ""isBusinessPurposeCompleted"": """",
                        ""customerNo"": """",
                        ""lineNumber"": 0,
                        ""l3CustomerHierarchy"": """",
                        ""salesOrg"": """",
                        ""customerDescription"": """",
                        ""customerGroup"": """",
                        ""currency"": """",
                        ""freeDefinedAttribute01"": """",
                        ""freeDefinedAttribute02"": """",
                        ""freeDefinedAttribute03"": """",
                        ""freeDefinedAttribute04"": """",
                        ""freeDefinedAttribute05"": """",
                        ""freeDefinedAttribute06"": """",
                        ""freeDefinedAttribute07"": """",
                        ""freeDefinedAttribute08"": """",
                        ""freeDefinedAttribute09"": """",
                        ""freeDefinedAttribute10"": """",
                        ""zz1CustomerNoHierarCus"": 0
                    },
                    ""toSupplierCompanyByPlant"": {
                        ""plant"": """",
                        ""supplier"": """",
                        ""valuationArea"": """",
                        ""companyCode"": """",
                        ""authorizationGroup"": """",
                        ""isBusinessPurposeCompleted"": """"
                    },
                    ""toCustomerCompanyByPlant"": {
                        ""plant"": """",
                        ""customer"": """",
                        ""valuationArea"": """",
                        ""companyCode"": """",
                        ""authorizationGroup"": """",
                        ""isBusinessPurposeCompleted"": """"
                    },
                    ""toItemExtension"": {
                        ""materialDocumentRecordType"": """",
                        ""materialDocument"": """",
                        ""materialDocumentYear"": 0,
                        ""materialDocumentItem"": 0
                    }
                },
                {
                    ""materialDocumentYear"": 2024,
                    ""materialDocument"": ""4900001565"",
                    ""materialDocumentItem"": 2,
                    ""material"": ""000000000000753741"",
                    ""plant"": ""1100"",
                    ""storageLocation"": ""0005"",
                    ""batch"": """",
                    ""goodsMovementType"": ""325"",
                    ""inventoryStockType"": ""07"",
                    ""inventoryValuationType"": """",
                    ""inventorySpecialStockType"": """",
                    ""supplier"": """",
                    ""customer"": """",
                    ""salesOrder"": """",
                    ""salesOrderItem"": 0,
                    ""salesOrderScheduleLine"": 0,
                    ""purchaseOrder"": """",
                    ""purchaseOrderItem"": 0,
                    ""wbsElement"": """",
                    ""manufacturingOrder"": """",
                    ""manufacturingOrderItem"": 0,
                    ""goodsMovementRefDocType"": """",
                    ""goodsMovementReasonCode"": 0,
                    ""delivery"": """",
                    ""deliveryItem"": 0,
                    ""accountAssignmentCategory"": """",
                    ""costCenter"": """",
                    ""controllingArea"": ""1000"",
                    ""costObject"": """",
                    ""glAccount"": """",
                    ""functionalArea"": """",
                    ""profitabilitySegment"": 0,
                    ""profitCenter"": ""1100000000"",
                    ""masterFixedAsset"": """",
                    ""fixedAsset"": """",
                    ""materialBaseUnit"": ""EA"",
                    ""quantityInBaseUnit"": 80.000,
                    ""entryUnit"": ""EA"",
                    ""quantityInEntryUnit"": 80.000,
                    ""companyCodeCurrency"": ""EUR"",
                    ""gdsMvtExtAmtInCoCdeCrcy"": 0,
                    ""amtInclVatInCoCodeCrcy"": 0,
                    ""fiscalYear"": 2024,
                    ""fiscalYearPeriod"": 2024010,
                    ""fiscalYearVariant"": ""K4"",
                    ""issgOrRcvgMaterial"": ""000000000000753741"",
                    ""issgOrRcvgBatch"": """",
                    ""issuingOrReceivingPlant"": ""1100"",
                    ""issgOrRcvgStorageLoc"": ""0001"",
                    ""issuingOrReceivingStockTyp"": ""07"",
                    ""issgOrRcvgSpclStockInd"": """",
                    ""issuingOrReceivingValType"": """",
                    ""isCompletelyDelivered"": """",
                    ""materialDocumentItemText"": """",
                    ""goodsRecipientName"": """",
                    ""unloadingPointName"": """",
                    ""shelfLifeExpirationDate"": """",
                    ""manufactureDate"": """",
                    ""serialNmbrAreCreatdAutomly"": """",
                    ""reservation"": 0,
                    ""reservationItem"": 0,
                    ""reservationIsFinallyIssued"": """",
                    ""specialStockIdfgSalesOrder"": """",
                    ""splStockIdfgSlsOrderItem"": 0,
                    ""specialStockIdfgWbsElement"": """",
                    ""isAutomaticallyCreated"": ""X"",
                    ""materialDocumentLine"": 2,
                    ""materialDocumentParentLine"": 1,
                    ""hierarchyNodeLevel"": 0,
                    ""goodsMovementIsCancelled"": """",
                    ""reversedMaterialDocumentYr"": 0,
                    ""reversedMaterialDocument"": """",
                    ""reversedMaterialDocumentItm"": 0,
                    ""referenceDocumentFiscalYear"": 0,
                    ""invtryMgmtRefDocumentItem"": 0,
                    ""invtryMgmtreferenceDocument"": """",
                    ""materialDocumentPostingType"": """",
                    ""inventoryUsabilityCode"": """",
                    ""ewmWarehouse"": """",
                    ""ewmStorageBin"": """",
                    ""crossPlantConfigurableProd"": """",
                    ""productCharacteristic1"": """",
                    ""productCharacteristic2"": """",
                    ""productCharacteristic3"": """",
                    ""productSeasonYear"": """",
                    ""productSeason"": """",
                    ""productCollection"": """",
                    ""productTheme"": """",
                    ""stockSegment"": """",
                    ""issgOrRcvgStockSegment"": """",
                    ""yyuniSuppCode"": ""A0081"",
                    ""debitCreditIndicator"": ""S"",
                    ""transactionCode"": ""MB1B"",
                    ""toSerialNumber"": [],
                    ""toSupplier"": {
                        ""supplier"": """",
                        ""alternativePayeeAccountNmbr"": """",
                        ""authorizationGroup"": """",
                        ""createdByUser"": """",
                        ""creationDate"": """",
                        ""customer"": """",
                        ""paymentIsBlockedForSupplr"": """",
                        ""postingIsBlocked"": """",
                        ""purchasingIsBlocked"": """",
                        ""supplierAccountGroup"": """",
                        ""supplierFullName"": """",
                        ""supplierName"": """",
                        ""vatRegistration"": """",
                        ""birthDate"": """",
                        ""concatInternationalLocNo"": """",
                        ""deletionIndicator"": """",
                        ""fiscalAddress"": """",
                        ""industry"": """",
                        ""internationalLocationNumber1"": 0,
                        ""internationalLocationNumber2"": 0,
                        ""internationalLocationNumber3"": 0,
                        ""isNaturalPerson"": """",
                        ""responsibleType"": """",
                        ""splrQltyInProcCrtfnValTo"": """",
                        ""suplrQualityManagementSys"": """",
                        ""supplierCorporateGroup"": """",
                        ""supplierProcurementBlock"": """",
                        ""taxNumber1"": """",
                        ""taxNumber2"": """",
                        ""taxNumber3"": """",
                        ""taxNumber4"": """",
                        ""taxNumber5"": """",
                        ""taxNumberResponsible"": """",
                        ""taxNumberType"": """",
                        ""suplrProofOfDelivRlvtCode"": """",
                        ""isBusinessPurposeCompleted"": """",
                        ""brTaxIsSplit"": """",
                        ""dataExchangeInstructionKey"": """"
                    },
                    ""toCustomer"": {
                        ""customer"": """",
                        ""authorizationGroup"": """",
                        ""billngIsBlockedForCustomer"": """",
                        ""createdByUser"": """",
                        ""creationDate"": """",
                        ""customerAccountGroup"": """",
                        ""customerClassification"": """",
                        ""customerFullName"": """",
                        ""customerName"": """",
                        ""deliveryIsBlocked"": """",
                        ""nfPartnerIsNaturalPerson"": """",
                        ""orderIsBlockedForCustomer"": """",
                        ""postingIsBlocked"": """",
                        ""supplier"": """",
                        ""customerCorporateGroup"": """",
                        ""fiscalAddress"": """",
                        ""industry"": """",
                        ""industryCode1"": """",
                        ""industryCode2"": """",
                        ""industryCode3"": """",
                        ""industryCode4"": """",
                        ""industryCode5"": """",
                        ""internationalLocationNumber1"": 0,
                        ""nielsenRegion"": """",
                        ""responsibleType"": """",
                        ""taxNumber1"": """",
                        ""taxNumber2"": """",
                        ""taxNumber3"": """",
                        ""taxNumber4"": """",
                        ""taxNumber5"": """",
                        ""taxNumberType"": """",
                        ""vatRegistration"": """",
                        ""deletionIndicator"": """",
                        ""expressTrainStationName"": """",
                        ""trainStationName"": """",
                        ""cityCode"": """",
                        ""county"": """",
                        ""isBusinessPurposeCompleted"": """",
                        ""customerNo"": """",
                        ""lineNumber"": 0,
                        ""l3CustomerHierarchy"": """",
                        ""salesOrg"": """",
                        ""customerDescription"": """",
                        ""customerGroup"": """",
                        ""currency"": """",
                        ""freeDefinedAttribute01"": """",
                        ""freeDefinedAttribute02"": """",
                        ""freeDefinedAttribute03"": """",
                        ""freeDefinedAttribute04"": """",
                        ""freeDefinedAttribute05"": """",
                        ""freeDefinedAttribute06"": """",
                        ""freeDefinedAttribute07"": """",
                        ""freeDefinedAttribute08"": """",
                        ""freeDefinedAttribute09"": """",
                        ""freeDefinedAttribute10"": """",
                        ""zz1CustomerNoHierarCus"": 0
                    },
                    ""toSupplierCompanyByPlant"": {
                        ""ohTest"": """",
                        ""plant"": """",
                        ""supplier"": """",
                        ""valuationArea"": """",
                        ""companyCode"": """",
                        ""authorizationGroup"": """",
                        ""isBusinessPurposeCompleted"": """"
                    },
                    ""toCustomerCompanyByPlant"": {
                        ""plant"": """",
                        ""customer"": """",
                        ""valuationArea"": """",
                        ""companyCode"": """",
                        ""authorizationGroup"": """",
                        ""isBusinessPurposeCompleted"": """"
                    },
                    ""toItemExtension"": {
                        ""materialDocumentRecordType"": """",
                        ""materialDocument"": """",
                        ""materialDocumentYear"": 0,
                        ""materialDocumentItem"": 0
                    }
                }
            ]
        }
    }
]
";
		var json = JsonSerializer.Deserialize<JsonElement>(jsontext);
		//act
		await sut.ProjectSchemaFlowAsync("BLAH", json);
	}
}
