name: Shared Application Integration Tests Workflow

on:
  workflow_call:
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: 'Azure Tenant ID'
      AZURE_CLIENT_ID:
        required: true
        description: 'Azure Client ID'
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: 'Azure Subscription ID'
      ACTIONS_AUTH_APP_ID:
        required: true
        description: 'GitHub App ID'
      ACTIONS_AUTH_APP_PRIVATE_KEY:
        required: true
        description: 'GitHub App Private Key'
    inputs:
      environment:
        type: string
        required: true
        description: 'Environment'
      applicationFolder:
        type: string
        required: true
        description: 'Application Folder'

jobs:
  run_integration_tests:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          path: mammon     

      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}

      - name: checkout devops-azure repo
        uses: actions/checkout@v3
        with:
          path: devops-azure
          repository: Uniphar/devops-azure
          token: ${{ steps.gh-app.outputs.token }}

      - name: checkout cost centre definition repo
        uses: actions/checkout@v3
        with:
          path: costcentre-definitions
          repository: Uniphar/costcentre-definitions
          ref: main
          token: ${{ steps.gh-app.outputs.token }}

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: compute environment variables
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          failOnStandardError: true
          inlineScript: |
            try{
              Import-Module ./devops-azure/src/Uniphar.DevOps.psd1 -ErrorAction Stop -Force

              $AzureKeyVaultName = Resolve-UniResourceName 'keyvault' "$p_devopsDomain-app" -Environment '${{ inputs.environment }}'

              echo "MAMMON_CONFIG_KEYVAULT_URL=https://$AzureKeyVaultName.vault.azure.net" >> $env:GITHUB_ENV
            }
            catch {
              Write-Error $_
              exit 1
            }

      - name: run integration tests
        working-directory: ./mammon/src/${{ inputs.applicationFolder }}.Tests
        run: dotnet test --filter TestCategory=IntegrationTest --logger "console;verbosity=normal"