name: Shared Application CI Workflow

on:
  workflow_call:
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: 'Azure Tenant ID'
      AZURE_CLIENT_ID:
        required: true
        description: 'Azure Client ID'
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: 'Azure Subscription ID'
      ACTIONS_AUTH_APP_ID:
        required: true
        description: 'GitHub App ID'
      ACTIONS_AUTH_APP_PRIVATE_KEY:
        required: true
        description: 'GitHub App Private Key'
    inputs:
      applicationFolder:
        type: string
        required: true
        description: Application Folder
      
jobs:
  app_ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}
          
      - name: checkout devops-azure repo
        uses: actions/checkout@v3
        with:
          path: devops-azure
          repository: Uniphar/devops-azure
          token: ${{ steps.gh-app.outputs.token }}

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9'

      - name: expose app name into env
        run: |
          echo "APPLICATION_FOLDER=${{ inputs.applicationFolder }}" >> $GITHUB_ENV
        
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: devops deploy WhatIf
        uses: azure/powershell@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #required for gh cli to determine "current PR"
        with: 
          inlineScript: |
            Import-Module .\devops-azure\src\Uniphar.DevOps.psd1 -ErrorAction Stop -Force
            . ./devops/Initialize-SapAct.ps1

            Initialize-SapAct dev -WhatIf
          azPSVersion: "latest"
          errorActionPreference: 'stop'
          failOnStandardError: true

      - name: run unit tests
        working-directory: ./src/${{ env.APPLICATION_FOLDER }}.Tests
        run: |
          dotnet test --filter TestCategory=Unit

      - name: docker build test
        working-directory: ./src/
        run: |
          docker build . -f ./$APPLICATION_FOLDER/Dockerfile
      
      - name: check for NuGet vulnerabilites
        working-directory: ./src/
        shell: pwsh
        run: |
            dotnet restore
            dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
            echo "Analyze dotnet list package command log output..."
            exit (Select-String -Path "build.log" -Pattern "has the following vulnerable packages" -AllMatches).Matches.Count -gt 0 ? 1 : 0

  notify:
    needs: app_ci
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && contains(needs.*.result, 'failure') }}
    steps:
      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}

      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'shared-failed-build-notification-workflow.yaml'
          inputs: '{
              "workflowId":"${{ github.run_id }}", 
              "repository":"${{ github.repository }}"
            }'
          token: ${{ steps.gh-app.outputs.token }}